name: package

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

jobs:
  zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: zip -r "GuildLink-${GITHUB_REF_NAME}.zip" GuildLink
      - uses: softprops/action-gh-release@v2
        with: { files: "GuildLink-*.zip" }
